@startuml Gerenciador de Eventos do Sistema

class MaquinaDeEventos {
    - _eventos: Evento[] 
    - _instanteDeSimulacao: number = 0
    + processarEventos(): Evento
    + adicionarEvento(novoEvento: Evento): void
    - atualizarInstanteDeSimulacao(novoInstanteDeSimulacao: number): void
}

class Evento {
    # _timeStamp: number
    # _refeitorio: Refeitorio 
    # _maquinaEventos: MaquinaDeEventos
    + getTimeStamp(): number
    + processarEvento(): void 
}

class ChegadaAlunoFilaExterna extends Evento {
    + processarEvento(): void
}

class PassarAlunoParaCatraca extends Evento {
    + processarEvento(): void
}

class PassarAlunoParaFilaInterna extends Evento {
    + processarEvento(): void
}

class ChegadaAlunoAtendimento extends Evento {
    + processarEvento(): void
}

class FinalizarAtendimentoAluno extends Evento {
    + processarEvento(): void
}

class PassarAlunoMesa extends Evento {
    + processarEvento(): void
}

class BloquearCatraca extends Evento {
    + processarEvento(): void
}

class DesbloquearCatraca extends Evento {
    + processarEvento(): void
}

class BloquearAtendimento extends Evento {
    + processarEvento(): void
}

class DesbloquearAtendimento extends Evento {
    + processarEvento(): void
}

MaquinaDeEventos -- "1..*" Evento
Evento -- "1..1" MaquinaDeEventos

@enduml