@startuml Gerenciador para Refeitorio 
class Aluno {
    +id: string
    +tempoEntradaFilaExterna: float
    +tempoNaCatraca: float
    +tempoServico: float
    +tempoPermanenciaMesa: float
}

class FilaExterna {
    +alunos: Aluno[]
    +distribuicaoChegada: string
    +intervaloAtendimento: float
    +adicionarAluno(aluno: Aluno): void
    +removerAluno(): Aluno
}

class Catraca {
    +alunoAtual: Aluno
    +tempoMedioDigitacao: float
    +limiteFilaInterna: int
    +quantidadeAlunosParaLiberar: int
    +bloqueada: boolean
    +verficaSeTemAlguem(aluno: Aluno): boolean
    +registrarEntrada(aluno: Aluno): void
    
}

class FilaInterna {
    +alunos: Aluno[]
    +limiteFilaInterna: int
    +adicionarAluno(aluno: Aluno): boolean
    +removerAluno(): Aluno
}

class Atendimento {
    +funcionariosDisponiveis: int
    +tempoMedioServico: float
    +distribuicaoServico: string
    +atenderAluno(aluno: Aluno): void
}

class Mesa {
    +limite: int
    +quantidadeOcupada: int
    +tempoMedioPermanencia: float
    +distribuicaoPermanencia: string
    +adicionarAluno(aluno: Aluno): boolean
    +removerAluno(): void
}

class Refeitorio {
    +filaExterna: FilaExterna
    +catraca: Catraca
    +filaInterna: FilaInterna
    +atendimento: Atendimento
    +mesas: Mesa[]
    +limiteMesas: int
    +iniciarSimulacao(): void
    +verificarDisponibilidade(): void
}

FilaExterna -- "1..*" Aluno : "contém"
FilaInterna -- "1..*" Aluno : "contém"
Catraca -- "1" Aluno : "registra entrada"
Atendimento -- "1" Aluno: "atende"
Mesa -- "1..*" Aluno : "tem"
Refeitorio -- "1" FilaExterna : "possui"
Refeitorio -- "1" Catraca : "possui"
Refeitorio -- "1" FilaInterna : "possui"
Refeitorio -- "1" Atendimento : "possui"
Refeitorio -- "1..*" Mesa : "possui"
@enduml
