@startuml Sistema 
class Aluno {
    -id: string
    -instanteDeChegada: number | undefined
    -tempoFilaExterna: number
    -tempoNaCatraca: number
    -tempoFilaInterna: number
    -tempoDeAtendimento: number
    -tempoPermanenciaMesa: number
}

class FilaExterna {
    -alunos: Aluno[]  = []
    +adicionarAlunoFilaExterna(aluno: Aluno): void
    +removerAluno(): Aluno
}

class Catraca {
    -alunoAtual: Aluno | undefined
    -tempoDePermanencia: number
    -quantidaDeAlunosParaLiberar: number
    -bloqueio: boolean
    +adicionarAlunoCatraca(aluno: Aluno): void
    +removerAlunoCatraca(): Aluno
}

class FilaInterna {
    -alunos: Aluno[] = []
    -limiteFilaInterna: number
    -tamanhoDaFila: number
    +adicionarAlunoFilaInterna(aluno: Aluno): boolean
    +removerAluno(): Aluno
}

class Atendimento {
    -alunoAtual = Aluno | undefined
    -tempoMedioServico: number
    -estaLiberado: boolean
    +adicionarAlunoAtendimento(aluno: Aluno): void
    +terminarAtendimento(aluno: Aluno): void
}

class Mesa {
    -alunos: Aluno[]
    -limite: number
    -tempoMedioPermanencia: number
    -alunoEstaNaMesa(id: string): boolean
    +adicionarAlunoMesa(aluno: Aluno): boolean
    +removerAluno(): void
}

class Refeitorio {
    -filaExterna: FilaExterna
    -catraca: Catraca
    -filaInterna: FilaInterna
    -atendimento: Atendimento
    -mesas: Mesa[]
    -chegadaAlunoFilaExterna(aluno: Aluno): boolean
    -catracaEstaVazia(): boolean
    -moverAlunoDaFilaExternaParaCatraca(aluno: Aluno): number
    -filaInternaEstaCheia(): boolean
    -moverAlunoDaCatracaParaFilaInterna(aluno: Aluno): number
    -atendimentoEstaVazio(): boolean
    -moverAlunoParaAtendimento(aluno: Aluno)
    -temMesaDisponivel(): boolean
    -finalizarAtendimento(aluno: Aluno)
    

}

FilaExterna -- "1..*" Aluno : "contém"
FilaInterna -- "1..*" Aluno : "contém"
Catraca -- "1" Aluno : "registra entrada"
Atendimento -- "1" Aluno: "atende"
Mesa -- "1..*" Aluno : "tem"
Refeitorio -- "1" FilaExterna : "possui"
Refeitorio -- "1" Catraca : "possui"
Refeitorio -- "1" FilaInterna : "possui"
Refeitorio -- "1" Atendimento : "possui"
Refeitorio -- "1..*" Mesa : "possui"
@enduml
